name: prova_flutter_login
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.1.1
  google_fonts: ^6.1.0
  mobx: ^2.2.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.6
  mobx_codegen: ^2.0.7+3

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
